apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: databases
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: archpo-platform
    app.kubernetes.io/managed-by: kubernetes-manifests
    app.kubernetes.io/component: dev-dependency
    archpo.local/alias-for: valkey
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: valkey
  ports:
    - name: redis
      port: 6379
      targetPort: redis
