apiVersion: v1
kind: Service
metadata:
  name: chromadb
  namespace: databases
  labels:
    app.kubernetes.io/name: chromadb
    app.kubernetes.io/part-of: archpo-platform
    app.kubernetes.io/managed-by: kubernetes-manifests
    app.kubernetes.io/component: dev-dependency
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chromadb
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: chroma
  namespace: databases
  labels:
    app.kubernetes.io/name: chromadb
    app.kubernetes.io/part-of: archpo-platform
    app.kubernetes.io/managed-by: kubernetes-manifests
    app.kubernetes.io/component: dev-dependency
    archpo.local/alias-for: chromadb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: chromadb
  ports:
    - name: http
      port: 8005
      targetPort: http
