apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-registry-data
  namespace: infra
  labels:
    app.kubernetes.io/name: local-registry
    app.kubernetes.io/part-of: archpo-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
