apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: databases
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: archpo-platform
    app.kubernetes.io/managed-by: kubernetes-manifests
    app.kubernetes.io/component: dev-dependency
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: minio
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console
