global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "severity"]
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "log-receiver"

  routes:
    - matchers:
        - severity = critical
      receiver: "log-receiver"
      repeat_interval: 15m

    - matchers:
        - severity = warning
      receiver: "log-receiver"
      repeat_interval: 30m

receivers:
  - name: "log-receiver"
    webhook_configs:
      - url: "http://pmi-agent:8006/api/v1/alerts"
        send_resolved: true
        http_config:
          follow_redirects: true

inhibit_rules:
  - source_matchers:
      - severity = critical
    target_matchers:
      - severity = warning
    equal: ["alertname"]
