apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres/initdb-configmap.yaml
  - postgres/postgres-statefulset.yaml
  - postgres/postgres-service.yaml
  - mongodb/mongodb-statefulset.yaml
  - mongodb/mongodb-service.yaml
  - valkey/valkey-deployment.yaml
  - valkey/valkey-service.yaml
  - valkey/redis-service-alias.yaml
  - minio/minio-deployment.yaml
  - minio/minio-service.yaml
  - minio/minio-buckets-job.yaml
  - chromadb/chromadb-deployment.yaml
  - chromadb/chromadb-service.yaml
