apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: databases
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: archpo-platform
    app.kubernetes.io/managed-by: kubernetes-manifests
    app.kubernetes.io/component: dev-dependency
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
