apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalog-service.fullname" . }}-config
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    {{- include "catalog-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.connections.kafka.enabled }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.connections.kafka.bootstrapServers | quote }}
  {{- end }}
  {{- if .Values.connections.redis.enabled }}
  REDIS_URL: {{ .Values.connections.redis.url | quote }}
  {{- end }}
  {{- if .Values.connections.mongodb.enabled }}
  MONGO_HOST: {{ .Values.connections.mongodb.host | quote }}
  MONGO_PORT: {{ .Values.connections.mongodb.port | quote }}
  MONGO_DB: {{ .Values.connections.mongodb.database | quote }}
  {{- end }}
