"""
Catalog Service — unit + integration tests.

JWT isolation  : test RSA key pair in tests/fixtures/ (generated by conftest).
DB isolation   : mongomock-motor in-memory MongoDB.
Auth API calls : no real Auth Service — JWKS_URL is empty, JWT_PUBLIC_KEY_PATH set.
"""
from __future__ import annotations
import pytest
from httpx import AsyncClient, ASGITransport

from tests.conftest import make_token


# ─── helpers ──────────────────────────────────────────────────────────────────

PROJECT = "proj-test-001"

def pm_headers() -> dict:
    token = make_token(roles=[{"project_id": PROJECT, "role": "pm", "side": "customer"}])
    return {"Authorization": f"Bearer {token}"}


def analyst_headers() -> dict:
    token = make_token(roles=[{"project_id": PROJECT, "role": "analyst", "side": "contractor"}])
    return {"Authorization": f"Bearer {token}"}


def admin_headers() -> dict:
    token = make_token(roles=[{"project_id": PROJECT, "role": "admin", "side": "customer"}])
    return {"Authorization": f"Bearer {token}"}


# ─── Unit tests ────────────────────────────────────────────────────────────────

def test_make_token_is_valid_jwt():
    """make_token produces a valid RS256 JWT verifiable with test public key."""
    import jwt as pyjwt
    from tests.conftest import PUBLIC_KEY_PATH

    token = make_token(roles=[{"project_id": PROJECT, "role": "pm", "side": "customer"}])
    public_key = PUBLIC_KEY_PATH.read_text()
    payload = pyjwt.decode(token, public_key, algorithms=["RS256"])
    assert payload["roles"][0]["role"] == "pm"


def test_require_project_role_grants_access():
    from app.api.deps import require_project_role, get_user_role_in_project
    from shared.schemas.user import TokenPayload, ProjectRole
    from uuid import UUID

    user = TokenPayload(
        sub=UUID("00000000-0000-0000-0000-000000000001"),
        org_id=UUID("00000000-0000-0000-0000-000000000002"),
        roles=[ProjectRole(project_id=UUID("00000000-0000-0000-0000-000000000003"), role="pm", side="customer")],
        exp=9999999999,
        iat=0,
    )
    # Should not raise
    require_project_role(["pm", "admin"], "00000000-0000-0000-0000-000000000003", user)


def test_require_project_role_forbids():
    from fastapi import HTTPException
    from app.api.deps import require_project_role
    from shared.schemas.user import TokenPayload, ProjectRole
    from uuid import UUID
    import pytest

    user = TokenPayload(
        sub=UUID("00000000-0000-0000-0000-000000000001"),
        org_id=UUID("00000000-0000-0000-0000-000000000002"),
        roles=[ProjectRole(project_id=UUID("00000000-0000-0000-0000-000000000003"), role="analyst", side="customer")],
        exp=9999999999,
        iat=0,
    )
    with pytest.raises(HTTPException) as exc_info:
        require_project_role(["pm"], "00000000-0000-0000-0000-000000000003", user)
    assert exc_info.value.status_code == 403


# ─── Integration: health ──────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_health(test_app):
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.get("/health")
    assert resp.status_code == 200
    assert resp.json()["status"] == "ok"


# ─── Integration: no auth → 401 ───────────────────────────────────────────────

@pytest.mark.asyncio
async def test_list_templates_requires_auth(test_app):
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.get("/api/catalog/templates")
    assert resp.status_code == 401


@pytest.mark.asyncio
async def test_list_functions_requires_auth(test_app):
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.get("/api/catalog/functions")
    assert resp.status_code == 401


# ─── Integration: templates ───────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_create_and_get_template(test_app):
    payload = {
        "type": "tz",
        "name": "Test TZ Template",
        "project_id": PROJECT,
        "sections": [],
    }
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.post("/api/catalog/templates", json=payload, headers=pm_headers())
    assert resp.status_code == 201, resp.text
    data = resp.json()
    tmpl_id = data["id"]
    assert data["name"] == "Test TZ Template"
    assert data["is_system"] is False

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.get(f"/api/catalog/templates/{tmpl_id}", headers=pm_headers())
    assert resp.status_code == 200
    assert resp.json()["id"] == tmpl_id


@pytest.mark.asyncio
async def test_analyst_cannot_create_template(test_app):
    payload = {"type": "chtz", "name": "Analyst Template", "project_id": PROJECT, "sections": []}
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.post("/api/catalog/templates", json=payload, headers=analyst_headers())
    assert resp.status_code == 403


@pytest.mark.asyncio
async def test_delete_system_template_forbidden(test_app):
    """System templates cannot be deleted by anyone."""
    from app.models.template import Template
    sys_tmpl = Template(
        id="tmpl-sys-test",
        type="tz",
        name="System template",
        is_system=True,
        created_at="",
        updated_at="",
    )
    await sys_tmpl.insert()

    token = make_token(is_superadmin=True)
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.delete(
            "/api/catalog/templates/tmpl-sys-test",
            headers={"Authorization": f"Bearer {token}"},
        )
    assert resp.status_code == 409
    assert resp.json()["error"]["code"] == "SYSTEM_TEMPLATE"


@pytest.mark.asyncio
async def test_update_template(test_app):
    payload = {"type": "pmi", "name": "Original Name", "project_id": PROJECT, "sections": []}
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        created = await c.post("/api/catalog/templates", json=payload, headers=pm_headers())
        tmpl_id = created.json()["id"]
        resp = await c.put(
            f"/api/catalog/templates/{tmpl_id}",
            json={"name": "Updated Name"},
            headers=pm_headers(),
        )
    assert resp.status_code == 200
    assert resp.json()["name"] == "Updated Name"
    assert resp.json()["version"] == 2


# ─── Integration: functions ───────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_create_list_function(test_app):
    fn_payload = {
        "project_id": PROJECT,
        "code": "ФБ-01",
        "name": "Аутентификация пользователей",
        "category": "security",
        "priority": "must",
        "description": "Система должна обеспечивать аутентификацию.",
    }
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.post("/api/catalog/functions", json=fn_payload, headers=pm_headers())
    assert resp.status_code == 201, resp.text
    fn = resp.json()
    assert fn["code"] == "ФБ-01"
    assert fn["status"] == "draft"

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.get(f"/api/catalog/functions?project_id={PROJECT}", headers=pm_headers())
    assert resp.status_code == 200
    assert resp.json()["total"] >= 1


@pytest.mark.asyncio
async def test_analyst_cannot_edit_cost_params(test_app):
    fn_payload = {
        "project_id": PROJECT,
        "code": "ФБ-COST",
        "name": "Cost test function",
        "category": "data_management",
        "priority": "should",
    }
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        created = await c.post("/api/catalog/functions", json=fn_payload, headers=pm_headers())
        fn_id = created.json()["id"]

        resp = await c.put(
            f"/api/catalog/functions/{fn_id}",
            json={"cost_params": {"labor_hours": 999}},
            headers=analyst_headers(),
        )
    assert resp.status_code == 403


@pytest.mark.asyncio
async def test_pm_can_edit_cost_params(test_app):
    fn_payload = {
        "project_id": PROJECT,
        "code": "ФБ-COST2",
        "name": "Cost test function 2",
        "category": "data_management",
        "priority": "should",
    }
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        created = await c.post("/api/catalog/functions", json=fn_payload, headers=pm_headers())
        fn_id = created.json()["id"]

        resp = await c.put(
            f"/api/catalog/functions/{fn_id}",
            json={"cost_params": {"labor_hours": 80}},
            headers=pm_headers(),
        )
    assert resp.status_code == 200
    assert resp.json()["cost_params"]["labor_hours"] == 80


@pytest.mark.asyncio
async def test_soft_delete_function(test_app):
    fn_payload = {
        "project_id": PROJECT,
        "code": "ФБ-DEL",
        "name": "To be deleted",
        "category": "reporting",
        "priority": "could",
    }
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        created = await c.post("/api/catalog/functions", json=fn_payload, headers=pm_headers())
        fn_id = created.json()["id"]

        resp = await c.delete(f"/api/catalog/functions/{fn_id}", headers=pm_headers())
        assert resp.status_code == 204

        resp = await c.get(f"/api/catalog/functions/{fn_id}", headers=pm_headers())
        assert resp.status_code == 404


# ─── Integration: subsystems ──────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_create_list_subsystem(test_app):
    payload = {"project_id": PROJECT, "code": "ПБ", "name": "Подсистема безопасности", "order": 1}
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.post("/api/catalog/subsystems", json=payload, headers=pm_headers())
    assert resp.status_code == 201
    sub = resp.json()
    assert sub["code"] == "ПБ"

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.get(f"/api/catalog/subsystems?project_id={PROJECT}", headers=pm_headers())
    assert resp.status_code == 200
    assert resp.json()["total"] >= 1


@pytest.mark.asyncio
async def test_delete_subsystem_with_functions_raises_409(test_app):
    from app.models.subsystem import Subsystem
    from app.models.function import Function
    from datetime import datetime, timezone

    now = datetime.now(timezone.utc).isoformat()
    sub = Subsystem(project_id=PROJECT, code="TST", name="Test sub", created_at=now, updated_at=now)
    await sub.insert()

    fn = Function(
        project_id=PROJECT,
        subsystem_id=sub.id,
        code="FN-TST",
        name="Test fn",
        category="reporting",
        status="active",
        created_at=now,
        updated_at=now,
    )
    await fn.insert()

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.delete(f"/api/catalog/subsystems/{sub.id}", headers=pm_headers())
    assert resp.status_code == 409
    assert resp.json()["error"]["code"] == "HAS_FUNCTIONS"


# ─── Integration: rates ───────────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_update_and_get_rates(test_app):
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.put(
            f"/api/catalog/rates/{PROJECT}",
            json={"default_rate_per_hour": 4000.0, "vat_rate": 0.20},
            headers=pm_headers(),
        )
    assert resp.status_code == 200
    assert resp.json()["default_rate_per_hour"] == 4000.0

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.get(f"/api/catalog/rates?project_id={PROJECT}", headers=pm_headers())
    assert resp.status_code == 200
    assert resp.json()["default_rate_per_hour"] == 4000.0


@pytest.mark.asyncio
async def test_analyst_cannot_update_rates(test_app):
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.put(
            f"/api/catalog/rates/{PROJECT}",
            json={"default_rate_per_hour": 1.0},
            headers=analyst_headers(),
        )
    assert resp.status_code == 403


# ─── Integration: documents ───────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_create_update_document(test_app):
    # Create template first
    tmpl_payload = {
        "type": "tz",
        "name": "TZ for doc test",
        "project_id": PROJECT,
        "sections": [
            {
                "number": "1",
                "title": "Общие сведения",
                "source": "manual",
                "fields": [
                    {"key": "system_name", "label": "Наименование", "type": "text", "required": True}
                ],
            }
        ],
    }
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        tmpl_resp = await c.post("/api/catalog/templates", json=tmpl_payload, headers=pm_headers())
        tmpl_id = tmpl_resp.json()["id"]

        doc_payload = {
            "project_id": PROJECT,
            "template_id": tmpl_id,
            "name": "ТЗ v1",
            "type": "tz",
            "data": {"sections": {"1": {"system_name": "ГИС ЖКХ"}}},
        }
        resp = await c.post("/api/catalog/documents", json=doc_payload, headers=pm_headers())
    assert resp.status_code == 201
    doc = resp.json()
    doc_id = doc["id"]
    assert doc["status"] == "draft"

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.put(
            f"/api/catalog/documents/{doc_id}",
            json={"data": {"sections": {"1": {"system_name": "ГИС ЖКХ v2"}}}},
            headers=pm_headers(),
        )
    assert resp.status_code == 200
    assert resp.json()["version"] == 2


@pytest.mark.asyncio
async def test_cannot_update_locked_document(test_app):
    from app.models.document import Document
    from datetime import datetime, timezone

    now = datetime.now(timezone.utc).isoformat()
    doc = Document(
        project_id=PROJECT,
        template_id="tmpl-tz-001",
        name="Locked doc",
        type="tz",
        status="pending",
        created_at=now,
        updated_at=now,
    )
    await doc.insert()

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.put(
            f"/api/catalog/documents/{doc.id}",
            json={"name": "Try to update"},
            headers=pm_headers(),
        )
    assert resp.status_code == 409
    assert resp.json()["error"]["code"] == "DOCUMENT_LOCKED"


@pytest.mark.asyncio
async def test_validate_document(test_app):
    tmpl_payload = {
        "type": "tz",
        "name": "TZ with required fields",
        "project_id": PROJECT,
        "sections": [
            {
                "number": "1",
                "source": "manual",
                "fields": [
                    {"key": "customer_name", "label": "Заказчик", "type": "text", "required": True}
                ],
            }
        ],
    }
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        tmpl_id = (await c.post("/api/catalog/templates", json=tmpl_payload, headers=pm_headers())).json()["id"]

        doc_id = (
            await c.post(
                "/api/catalog/documents",
                json={"project_id": PROJECT, "template_id": tmpl_id, "name": "Draft doc", "type": "tz"},
                headers=pm_headers(),
            )
        ).json()["id"]

        resp = await c.post(f"/api/catalog/documents/{doc_id}/validate", headers=pm_headers())
    assert resp.status_code == 200
    result = resp.json()
    assert result["is_valid"] is False
    assert any("customer_name" in e for e in result["errors"])


# ─── Integration: internal API ────────────────────────────────────────────────

@pytest.mark.asyncio
async def test_internal_audit_requires_secret(test_app):
    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.get("/internal/audit")
    assert resp.status_code == 403


@pytest.mark.asyncio
async def test_internal_audit_with_secret(test_app):
    from app.config import get_settings
    secret = get_settings().INTERNAL_API_SECRET

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.get("/internal/audit", headers={"X-Internal-Secret": secret})
    assert resp.status_code == 200
    assert "items" in resp.json()


@pytest.mark.asyncio
async def test_render_bundle_not_found(test_app):
    from app.config import get_settings
    secret = get_settings().INTERNAL_API_SECRET

    async with AsyncClient(transport=ASGITransport(app=test_app), base_url="http://test") as c:
        resp = await c.get(
            "/internal/documents/nonexistent-doc/render-bundle",
            headers={"X-Internal-Secret": secret},
        )
    assert resp.status_code == 404
