apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: databases
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: archpo-platform
    app.kubernetes.io/managed-by: kubernetes-manifests
    app.kubernetes.io/component: dev-dependency
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: databases
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: archpo-platform
    app.kubernetes.io/managed-by: kubernetes-manifests
    app.kubernetes.io/component: dev-dependency
    archpo.local/alias-for: mongodb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
