---
kafka_namespace: kafka
strimzi_version: "0.46.0"
kafka_cluster_name: archpo-kafka
kafka_topic_name: gost34.workflow.events
kafka_user_name: archpo-app
kafka_replicas: 1
kafka_topic_partitions: 1
kafka_topic_replicas: 1
kafka_storage_type: ephemeral
kafka_plain_listener: true
kafka_tls_listener: false
kafka_user_enabled: false

kafka_version: "4.0.0"
kafka_metadata_version: "4.0-IV3"

kafka_resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "1"

strimzi_operator_manifest_url: "https://github.com/strimzi/strimzi-kafka-operator/releases/download/{{ strimzi_version }}/strimzi-cluster-operator-{{ strimzi_version }}.yaml"
strimzi_operator_manifest_path: "/tmp/strimzi-cluster-operator-{{ strimzi_version }}-{{ kafka_namespace }}.yaml"
