apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: archpo-platform
spec:
  project: default
  source:
    repoURL: https://github.com/nxtsurprised/ArchPO-the-2th-sem.git
    targetRevision: part-3
    path: platform/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
