apiVersion: v1
kind: Secret
metadata:
  name: kaniko-docker-config
  namespace: infra
  labels:
    app.kubernetes.io/name: kaniko
    app.kubernetes.io/part-of: archpo-cicd
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "local-registry.infra.svc.cluster.local:5000": {
          "auth": "base64-username-password-placeholder"
        }
      }
    }
