apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-auth-service-example
  namespace: infra
  labels:
    app.kubernetes.io/name: kaniko
    app.kubernetes.io/part-of: archpo-cicd
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:v1.23.2
          args:
            - --context=git://github.com/nxtsurprised/ArchPO-the-2th-sem.git#refs/heads/part-3
            - --context-sub-path=part1
            - --dockerfile=auth-service/Dockerfile
            - --destination=local-registry.infra.svc.cluster.local:5000/auth-service:example
            - --insecure
            - --skip-tls-verify
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
