apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  annotations:
    archpo.local/status: "placeholder"
spec:
  project: default
  source:
    repoURL: https://github.com/nxtsurprised/ArchPO-the-2th-sem.git
    targetRevision: part-3
    path: platform/gitops/services/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
