apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generation-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nxtsurprised/ArchPO-the-2th-sem.git
    targetRevision: part-3
    path: platform/helm/generation-service
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
