apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: observability
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.observability.svc.cluster.local:9090
        isDefault: true
        editable: true
      - name: Loki
        uid: Loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
        editable: true
      - name: Tempo
        uid: Tempo
        type: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3200
        editable: true
        jsonData:
          tracesToLogsV2:
            datasourceUid: Loki
            spanStartTimeShift: -5m
            spanEndTimeShift: 5m
            filterByTraceID: true
            filterBySpanID: false
          serviceMap:
            datasourceUid: Prometheus
